name: update-site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # запускается каждый час

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting job..."

      - name: Клонируем репозиторий
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0 # нужно для git pull

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запускаем обновление
        run: python jenmusic_updater.py

      - name: Настройка Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Подтягиваем изменения с origin/main
        run: git pull origin main --rebase

      - name: Коммит и пуш изменений
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add docs/log.json
            git commit -m "Auto update site content"
            git push origin main
          else
            echo "Нечего коммитить"
          fi
