name: JenMusic Auto Update

on:
  # запуск по расписанию и вручную
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Устанавливаем зависимости
        run: pip install beautifulsoup4 requests

      - name: Запускаем обновление
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Запускаем процесс обновления"
          python3 jenmusic_updater.py

      - name: Коммит и пуш изменений
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/index.html docs/saved_links.json
          git commit -m "Auto update JenMusic site" || echo "Нечего коммитить"
          git push
