name: update-site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запускаем обновление
        run: python jenmusic_updater.py

      - name: Настройка Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Подтягиваем изменения из origin/main
        run: git pull origin main --rebase || true

      - name: Коммит и пуш изменений
        run: |
          git add docs/log.json
          if git diff --cached --quiet; then
            echo "Нечего коммитить"
          else
            git commit -m "Auto update site content"
            git push origin main
          fi
