name: update-site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/saved_links.json
      - jenmusic_updater.py

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: Запускаем обновление
        run: python jenmusic_updater.py

      - name: Коммит и пуш изменений
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/saved_links.json
          git commit -m "Auto update saved_links.json" || echo "Нечего коммитить"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
