name: JenMusic Auto Update

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Устанавливаем зависимости
        run: pip install beautifulsoup4 requests

      - name: Запускаем обновление
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo 'Запускаем процесс обновления'
          python3 <<EOF
import os
token = os.environ['TELEGRAM_TOKEN']
chat_id = os.environ['TELEGRAM_CHAT_ID']

from bs4 import BeautifulSoup
import requests, json

# Вставь сюда код из jenmusic_auto_updater.py / ipynb
# или импортируй, если хочешь

# Пример финального вызова:
# process_all_new(token, chat_id)
EOF

      - name: Коммит и пуш
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html log.json
          git commit -m "Auto update JenMusic site"
          git push
