name: JenMusic Auto Update

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Устанавливаем зависимости
        run: pip install beautifulsoup4 requests

      - name: Запускаем обновление
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo 'Запускаем процесс обновления'
          python3 <<EOF
import os
token = os.environ['TELEGRAM_TOKEN']
chat_id = os.environ['TELEGRAM_CHAT_ID']

from bs4 import BeautifulSoup
import requests, json

- name: Запускаем обновление
  env:
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  run: |
    echo "Запускаем процесс обновления"

    python3 <<EOF
    import os
    import requests, json
    from bs4 import BeautifulSoup

    token = os.environ['TELEGRAM_TOKEN']
    chat_id = os.environ['TELEGRAM_CHAT_ID']

    # пример вызова функции из внешнего файла (если понадобится)
    # from jenmusic_updater import process_all_links
    # process_all_links(token, chat_id)

    print(f"Token: {token[:4]}..., ChatID: {chat_id}")
    EOF


      - name: Коммит и пуш
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html log.json
          git commit -m "Auto update JenMusic site"
          git push
